### ISSUE TITLE
Compressing certain dweets lead to `URI malformed` error and a blank page

### ISSUE THREAD

**Issue by lionleaf** [dwitter-net/dwitter-frontend#98]
When using the compression function on certain dweets, `encodeURIComponent(code)` in `DweetCard.tsx` fails with `URIError: URI malformed` which results in a white page. (React fails to render?)

For example this dweet: https://beta.dwitter.net/d/24252

PS: Thanks to u/xen for finding this one

**Comment by CiaccoDavide** [comment]
Related PR: https://github.com/dwitter-net/dwitter-frontend/pull/93
A similar thing was happening there, but I guess I didn't solve it completely...

**Comment by CiaccoDavide** [comment]
Fun fact:
this is the uncompressed dweet
![2021_10_30_21_53_024_firefox_Dwitter net_-_Javascript_demos_in_140_characters_](https://user-images.githubusercontent.com/3226096/139556829-11712139-6882-488d-8005-ce9c390dea25.png)

this is how the compressed one renders:
![image](https://user-images.githubusercontent.com/3226096/139556846-12efe680-7a12-4995-b5c9-4180ef348aa1.png)

**Comment by CiaccoDavide** [comment]
I've added a try/catch to the compression toggle in order to show an error when the `encodeURIComponent` can't encode the dweet correctly

This particular problem is caused by this emoji: 😶

https://user-images.githubusercontent.com/3226096/139557456-de96acba-28b1-452c-9c57-302a409e589a.mp4

If the 😶 is removed, the other ones will be compressed almost correctly...the compressor loses the unicode data, just like on "main dwitter"

https://user-images.githubusercontent.com/3226096/139557605-77d48079-2aac-48ed-a5d2-6dbf03d27eb1.mp4
